theme: jekyll-theme-cayman

title:            Learning & Reasoning
description:      The Learning & Reasoning group at Vrije Universiteit Amsterdam

defaults:
  -
    scope:
        path: ""
    values:
        article: false  # Whether this is an article page.
        maps: false     # Whether to load the google maps stuff.
        highlight: None # Which highlight to display: 0, 1, 2, 3... (front page only).
        dark: false     # Whether the menu is in dark mode.
        class: ''       # Will be added to the class attributed of the body tag for styling
        js: false       # If the page requires custom javascript
